-- Run in Supabase -> SQL Editor. Keep SUPABASE_KEY server-side only; use service_role key.
create table if not exists google_tokens (
  device_id text primary key,
  refresh_token text not null,
  email text,
  updated_at timestamptz default now()
);
alter table google_tokens enable row level security;

create table if not exists contacts (
  device_id text not null,
  name text not null,
  email text not null,
  updated_at timestamptz default now(),
  primary key (device_id, email)
);
alter table contacts enable row level security;

create table if not exists email_history (
  id bigint generated by default as identity primary key,
  device_id text not null,
  recipient_email text not null,
  subject text not null,
  body text not null,
  created_at timestamptz default now()
);
create index if not exists email_history_device_recipient_date_idx on email_history(device_id, recipient_email, created_at desc);
alter table email_history enable row level security;
-- No client-facing policies: the server accesses these tables with the service_role key.

-- WhatsApp contacts (added with the WhatsApp feature). Safe to run again.
create table if not exists whatsapp_contacts (
  device_id text not null,
  name text not null,
  phone text not null,
  updated_at timestamptz default now(),
  primary key (device_id, phone)
);
alter table whatsapp_contacts enable row level security;
